#!/bin/python3
import os

#add script's directory to PATH
__location__ = os.path.realpath(
    os.path.join(os.getcwd(), os.path.dirname(__file__)))

header = open(os.path.join(__location__, "header.html"), "r")
footer = open(os.path.join(__location__, "footer.html"), "r")
links = open(os.path.join(__location__, "links.txt"), "r")
out = open(os.path.join(__location__, "links.html"), "w")

out.write(header.read())

line = links.readline()
state = "TITLE"
while(line):
    print(line, end="")
    if state == "TITLE":
        out.write("<p>" + line + "</p>\n")
        state = "LINKS"
    elif state == "LINKS":
        if line == "\n":
            state = "TITLE"
            out.write("<br>\n")
        else:
            out.write("<a class=\"links\" href=\"" + line + "\">" + line + "</a><br>\n")

    line = links.readline()

out.write("<br><br><br><p><i>This page was generated by</i></p>\n")
out.write("<a href=\"genlinks.py\">genlinks.py</a><br>\n")
out.write("<a href=\"links.txt\">links.txt</a><br>\n")
out.write(footer.read())
			

    




